package nodal

// Generated by scripts/generate_analog_function_registry.py. Do not edit.
private[nodal] object AnalogFunctionRegistry:
  val Version = "1"
  val FunctionPrefix = "analog_function_v1_"
  val AnalysisPrefix = "analog_analysis_v1_"
  final case class Entry(id: String, arity: Int, dimensionRule: String, verilogA: String)
  val entries: Vector[Entry] = Vector(
    Entry("abs", 1, "preserve", "abs"),
    Entry("min", 2, "same", "min"),
    Entry("max", 2, "same", "max"),
    Entry("sqrt", 1, "sqrt", "sqrt"),
    Entry("hypot", 2, "same", "hypot"),
    Entry("atan2", 2, "ratio", "atan2"),
    Entry("pow", 2, "dimensionless", "pow"),
    Entry("exp", 1, "dimensionless", "exp"),
    Entry("ln", 1, "dimensionless", "ln"),
    Entry("log10", 1, "dimensionless", "log"),
    Entry("sin", 1, "dimensionless", "sin"),
    Entry("cos", 1, "dimensionless", "cos"),
    Entry("tan", 1, "dimensionless", "tan"),
    Entry("asin", 1, "dimensionless", "asin"),
    Entry("acos", 1, "dimensionless", "acos"),
    Entry("atan", 1, "dimensionless", "atan"),
    Entry("sinh", 1, "dimensionless", "sinh"),
    Entry("cosh", 1, "dimensionless", "cosh"),
    Entry("tanh", 1, "dimensionless", "tanh"),
    Entry("asinh", 1, "dimensionless", "asinh"),
    Entry("acosh", 1, "dimensionless", "acosh"),
    Entry("atanh", 1, "dimensionless", "atanh"),
    Entry("floor", 1, "dimensionless", "floor"),
    Entry("ceil", 1, "dimensionless", "ceil")
  )
  def analysisId(kind: AnalysisKind): String = kind match
    case AnalysisKind.Initialization => "initialization"
    case AnalysisKind.Dc => "dc"
    case AnalysisKind.OperatingPoint => "operating_point"
    case AnalysisKind.Transient => "transient"
    case AnalysisKind.Ac => "ac"
    case AnalysisKind.Noise => "noise"
  val analysisTargets: Map[String, String] = Map(
    "initialization" -> "ic",
    "dc" -> "dc",
    "operating_point" -> "static",
    "transient" -> "tran",
    "ac" -> "ac",
    "noise" -> "noise"
  )
