#!/usr/bin/env python3
"""Generate closed registry tables; --check rejects stale generated contracts."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    registry = json.loads((ROOT / "core/compiler/analog-functions-v1.json").read_text())
    assert registry["schema_version"] == 1 and registry["registry_version"] == "1"
    functions, analyses = registry["functions"], registry["analyses"]
    assert len({x["id"] for x in functions}) == len(functions)
    scala = ["package nodal", "", "// Generated by scripts/generate_analog_function_registry.py. Do not edit.",
             "private[nodal] object AnalogFunctionRegistry:", '  val Version = "1"',
             '  val FunctionPrefix = "analog_function_v1_"', '  val AnalysisPrefix = "analog_analysis_v1_"',
             "  final case class Entry(id: String, arity: Int, dimensionRule: String, verilogA: String)",
             "  val entries: Vector[Entry] = Vector("]
    scala += [f'    Entry("{f["id"]}", {f["arity"]}, "{f["dimension_rule"]}", "{f["verilog_a"]}")' +
              ("," if i + 1 < len(functions) else "") for i, f in enumerate(functions)]
    scala += ["  )", "  def analysisId(kind: AnalysisKind): String = kind match"]
    scala += [f'    case AnalysisKind.{a["scala"]} => "{a["id"]}"' for a in analyses]
    scala += ["  val analysisTargets: Map[String, String] = Map("]
    scala += [f'    "{a["id"]}" -> "{a["verilog_a"]}"' + ("," if i + 1 < len(analyses) else "")
              for i, a in enumerate(analyses)]
    scala += ["  )", ""]
    native = ["// Generated by scripts/generate_analog_function_registry.py. Do not edit.",
              "static constexpr AnalogFunctionEntry functionEntries[] = {"]
    native += [f'    {{"{f["id"]}", {f["arity"]}, "{f["dimension_rule"]}", "{f["verilog_a"]}"}},'
               for f in functions]
    native += ["};", "static constexpr AnalogAnalysisEntry analysisEntries[] = {"]
    native += [f'    {{"{a["id"]}", "{a["verilog_a"]}"}},' for a in analyses]
    native += ["};", ""]
    return {"core/scala/api/src/nodal/AnalogFunctionRegistry.scala": "\n".join(scala),
            "core/compiler/include/nodal/Dialect/Nodal/AnalogFunctionRegistry.inc": "\n".join(native)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale registry: {name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
